# Generated by Django 5.1.3 on 2024-11-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_student_gender_subjecttab_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Studenttab',
        ),
    ]
