# Generated by Django 5.1.3 on 2024-11-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_student_studenttab'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttab',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studenttab',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
